[features]
seeds = false
skip-lint = false
[programs.localnet]
math = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
canvas = "9ZpEywiXTgkHMAxZgjgBffGbyJBBu6pekFmhu6iFezp4"
artist = "CT72WNsv3kjdnesJzh5Ma9CebSyYCJJ2uUDxfjvUPjnK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/way/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
